### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by devMunyi** [devMunyi/Recipe-App#9]
Link to the [project kanban board](https://github.com/users/devMunyi/projects/5)

Two Members:

- @devMunyi 
- @tarikbouari

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @devMunyi and @tarikbouari,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You should provide the link to your Kanban board, not your repository

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by omar-muhamad** [comment]
# Invalid ❌

Hi Team,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Your Code Review Request is marked as invalid for these reasons:

- [ ] The link you provided is broken, Please add a valid project link.

![image](https://user-images.githubusercontent.com/68796232/216972293-c47832c8-efa2-4740-830a-0d1736c901da.png)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by devMunyi** [comment]
@Omar-Muhamad,  Oooops! I don't understand what's happening. I'm able to open the same link which is not opening on your side:
![Screenshot from 2023-02-06 16-00-23](https://user-images.githubusercontent.com/46225052/216978197-60a8a512-5595-47a1-9a64-fea83e7bbbbb.png)

**Comment by tarikbouari** [comment]
The link issue is solved. you can go ahead and make the review dear reviewer.

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @devMunyi and @tarikbouari,

✔️ Tasks are well assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
